### PR TITLE
Move ibeaschool.org from using SquareSpace to using local html files

### PR DESCRIPTION
**Pull request by tanvibhakta**
This PR moves us away from using (and being limited by) the SquareSpace editor for this website, and allows us to embed a RazorPay-powered 'Donate' button on our donate page. The website is hosted on Netlify, under my account.

We made the decision to move away from SquareSpace because their subscriptions are expensive for NGOs based in India, and having to pay an additional $60 a year to be able to have our donate button, on top of the $144 of the regular subscription, was not viable (the first year was a gift from one of the patrons). 

We still have the subscription for 10 months, so all our assets still live there, primarily images. We are also using SquareSpace animations.

### Images

When deactivating our SquareSpace instance, we should just use local images (run through image-optim) and continue hosting on Netlify.
If the website becomes too slow and unwieldy, it is perhaps a good idea to move to Cloudinary - they have an acceptable free tier.

### Animations
It's okay if they don't exist 😅. That can also be a problem for Future Tanvi, who is hopefully more well-informed of simple animation libraries than I am :)

### CODE REVIEW

**Comment by tanvibhakta** [comment]
@deobald could you have a look at this when you have the time? I don't think I have the rights to assign this to you, sorry :P

**Comment by tanvibhakta** [comment]
@lifeeth, I spoke to Steve and he doesn't have the (literal, internet) bandwidth for this right now. :D Do you think you have the space to just look this over once before merge?

**Comment by lifeeth** [comment]
Sure. But please give me till tomorrow end of day.

**Comment by lifeeth** [comment]
Sorry this took more time.

The image on the front fold is missing. Probably because the squarespace js is trying to load settings from an endpoint "https://deploy-preview-1--elastic-pike-e36b4a.netlify.app/api/1/performance/settings" - Which does not exist when hosted on netlify. Looks good otherwise.

**Pull request merged**
